# Generated by Django 3.0.2 on 2020-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0005_auto_20200215_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('EnrollMent', models.CharField(max_length=30)),
                ('Branch', models.CharField(max_length=10)),
            ],
        ),
    ]
